name: bridge-development-actions
run-name: Development server deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
      - run: mkdir -p ~/.ssh
      - run: echo '${{ secrets.SSH_KEY }}' | tr -d '\r' > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: eval ssh-agent -s && ssh-add ~/.ssh/id_rsa
      - run: ssh-keyscan "${{ vars.DEV_SITE_ADDRESS }}" >> ~/.ssh/known_hosts
      - run: which rsync || (apt update -y && apt install rsync -y)
      - run: rsync -rvz --delete --no-perms --no-group --no-owner --ignore-missing-args --rsh='ssh ubuntu@"${{ vars.DEV_SITE_ADDRESS }}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ${{ github.workspace }}/remui/. :"${{ vars.DIRECTORY }}"
